twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - India Politics
    - Technology
    - Layoffs
    - Kafka
    - ElasticSearch
    - Elon Musk
    - Narendra Modi


